site_name: Metodika pro správu metadatových profilů
nav:
  - Úvod: index.md
  - Aplikační profil: profil.md
  - Datové modelování: modelovani.md
site_url: https://libcas.github.io/Metodika-Dataspecer/
site_dir: site
repo_url: https://github.com/LIBCAS/Metodika-Dataspecer
edit_uri: https://github.com/LIBCAS/Metodika-Dataspecer/tree/main/docs