site_name: Metodika pro správu metadatových profilů
nav:
  - Úvod: index.md
  - Dataspecer: dataspecer.md
  - Editor modelu: editor-modelu.md
  - Aplikační profily: aplikační-profily.md
  - Slovníky: slovníky.md
  - Slovník pojmů: slovník-pojmů.md
site_url: https://libcas.github.io/Metodika-Dataspecer/
site_dir: site
theme:
  name: material
  language: cs
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/libcas/Metodika-Dataspecer
  generator: false